[package]
name = "nuna-marketplace"
version = "1.0.0"
edition = "2021"
authors = ["Nuna Curate Team"]

[lib]
crate-type = ["cdylib"]

[dependencies]
soroban-sdk = { workspace = true }
soroban-token-sdk = { workspace = true }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }

[features]
testutils = ["soroban-sdk/testutils"]
